name: CI Checks & Build

on:
  push:
    branches: ["main", "develop", "api-report"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: "CI Build"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: NPM Install
        run: npm install --silent

      - name: Lint Check
        run: npm run lint

      - name: Bundle
        run: npm run build

      - name: Add dist bundle
        if: github.ref == 'refs/heads/api-report' && github.event_name == 'push'
        run: |
          git config --local user.email "walter1008@gmail.com"
          git config --local user.name "waltervr"
          git add --force dist
          git commit -m "CI automation $(date)"

      - name: Push changes
        if: github.ref == 'refs/heads/api-report' && github.event_name == 'push'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: api-report
          force: true
